# Generated by Django 4.1.5 on 2023-02-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_variation"),
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="variation",
            field=models.ManyToManyField(blank=True, to="store.variation"),
        ),
    ]
