# Generated by Django 4.1.5 on 2023-05-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="zip",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
