# Generated by Django 4.1.5 on 2023-05-20 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_order_payment"),
    ]

    operations = [
        migrations.RemoveField(model_name="orderproduct", name="color",),
        migrations.RemoveField(model_name="orderproduct", name="size",),
    ]
