# Generated by Django 4.1.5 on 2023-05-21 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_remove_orderproduct_variation_orderproduct_variation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderproduct",
            old_name="product_price",
            new_name="productPrice",
        ),
    ]
